-- ==============================================================================
-- PROJECT: Internship & Placement Tracking System
-- ROLE: Supabase Engineer / Database Administrator
-- ==============================================================================

-- 1. STUDENTS TABLE
-- Stores student profile information, academics, and resume metadata
CREATE TABLE public.students (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    department TEXT,
    cgpa NUMERIC(4,2),
    skills JSONB, -- Array of strings
    resumes JSONB, -- Array of uploaded resume objects/URLs
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. JOBS TABLE
-- Stores AI-ingested jobs from LinkedIn, Naukri, etc.
CREATE TABLE public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    location TEXT,
    salary TEXT,
    skills_required TEXT, -- Comma separated or JSON
    application_link TEXT,
    platform_source TEXT,
    deadline TIMESTAMP WITH TIME ZONE,
    job_type TEXT DEFAULT 'Full-time',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. APPLICATIONS TABLE
-- Connects students to jobs, tracks status and AI match percentage
CREATE TABLE public.applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
    job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'Pending', -- Pending, Selected, Rejected
    match_percentage INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. ROYLES & SECURITY POLICIES (Row Level Security)
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- Allow students to only see/edit their own data
CREATE POLICY "Students can view own profile" 
    ON public.students FOR SELECT 
    USING ( auth.uid() = id );

CREATE POLICY "Students can manage own applications" 
    ON public.applications FOR ALL 
    USING ( auth.uid() = student_id );

-- Allow all authenticated users to read jobs
CREATE POLICY "Anyone can view jobs" 
    ON public.jobs FOR SELECT 
    USING ( true );
